version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"  # A porta do DynamoDB Local continua sendo 8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ./data:/home/dynamodblocal/data  # Caminho do volume ajustado
    networks:
      - app-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"  # Corrigido de "dynamodb-local" para "dynamodb"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    networks:
      - app-network  # Certifique-se de que o dynamodb-admin está na mesma rede

networks:
  app-network:
    driver: bridge

volumes:
  dynamodb-data:
